"use client";

import {
  MessageSquare,
  Key,
  Copy,
  Check,
  Trash2
} from "lucide-react";
import { DiscordStatus, TokenItem } from "./types";
import { useTheme } from "@/lib/useTheme";

interface SettingsViewProps {
  discordStatus: DiscordStatus | null;
  linkCode: string;
  setLinkCode: (code: string) => void;
  linkMessage: { type: "success" | "error"; text: string } | null;
  linkDiscord: () => Promise<void>;
  unlinkDiscord: () => Promise<void>;
  tokens: TokenItem[];
  newTokenName: string;
  setNewTokenName: (name: string) => void;
  generatedToken: string | null;
  setGeneratedToken: (token: string | null) => void;
  generateToken: () => Promise<void>;
  deleteToken: (tokenId: string) => Promise<void>;
  copyToClipboard: (text: string) => void;
  copied: boolean;
}

export default function SettingsView({
  discordStatus,
  linkCode,
  setLinkCode,
  linkMessage,
  linkDiscord,
  unlinkDiscord,
  tokens,
  newTokenName,
  setNewTokenName,
  generatedToken,
  setGeneratedToken,
  generateToken,
  deleteToken,
  copyToClipboard,
  copied
}: SettingsViewProps) {
  const { theme, changeTheme } = useTheme();

  return (
    <div className="space-y-6 max-w-2xl">
      <div>
        <h2 className="text-2xl font-bold text-zinc-100 mb-1 select-none">Settings</h2>
        <p className="text-sm text-zinc-400 select-none">Manage appearance, Discord pairing codes, and MCP client tokens.</p>
      </div>

      {/* Appearance Section */}
      <div className="rounded-2xl border border-white/10 bg-white/[0.02] p-6 space-y-4">
        <div className="flex items-center gap-3 select-none">
          <div className="p-2 bg-white/5 rounded-lg border border-white/10">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="20"
              height="20"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
              className="h-5 w-5 text-zinc-300"
            >
              <path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z" />
            </svg>
          </div>
          <div>
            <h3 className="text-md font-semibold text-zinc-100 font-bold">Appearance</h3>
            <p className="text-xs text-zinc-400">Customize the application interface color scheme.</p>
          </div>
        </div>

        <div className="grid grid-cols-3 gap-3">
          {(["dark", "light", "gray"] as const).map((t) => (
            <button
              key={t}
              onClick={() => changeTheme(t)}
              className={`flex flex-col items-center gap-2 p-3.5 rounded-xl border transition-all cursor-pointer select-none text-xs md:text-sm font-semibold capitalize ${
                theme === t
                  ? "bg-white text-zinc-950 border-white shadow-[0_0_15px_rgba(255,255,255,0.1)] font-bold scale-[1.02]"
                  : "bg-white/[0.02] text-zinc-300 border-white/5 hover:border-white/15 hover:bg-white/[0.05]"
              }`}
            >
              {t === "gray" ? "Discord Gray" : t}
            </button>
          ))}
        </div>
      </div>

      {/* Discord Section */}
      <div className="rounded-2xl border border-white/10 bg-white/[0.02] p-6 space-y-4">
        <div className="flex items-center gap-3 select-none">
          <div className="p-2 bg-white/5 rounded-lg border border-white/10">
            <MessageSquare className="h-5 w-5 text-zinc-300" />
          </div>
          <div>
            <h3 className="text-md font-semibold text-zinc-100 font-bold">Discord Integration</h3>
            <p className="text-xs text-zinc-400">Sync and operate tasks using bot commands.</p>
          </div>
        </div>

        {discordStatus?.discordId ? (
          <div className="space-y-3">
            <div className="flex items-center gap-2 text-sm text-emerald-400 bg-emerald-500/10 border border-emerald-500/20 px-4 py-2.5 rounded-xl">
              <Check className="h-4 w-4" />
              <span>Linked to Discord: <strong className="select-text">{discordStatus.username ? `${discordStatus.username} (${discordStatus.discordId})` : discordStatus.discordId}</strong></span>
            </div>
            <button
              onClick={unlinkDiscord}
              className="px-4 py-2 text-xs font-semibold rounded-lg bg-red-500/10 border border-red-500/20 text-red-400 hover:bg-red-500/20 transition-all cursor-pointer"
            >
              Unlink Account
            </button>
          </div>
        ) : (
          <div className="space-y-3">
            <p className="text-xs text-zinc-400 select-none">
              Enter the 6-digit code generated by the <code className="bg-white/5 px-1.5 py-0.5 rounded text-white font-mono">/todo link</code> command in Discord:
            </p>
            <div className="flex gap-2 max-w-xs font-mono">
              <input
                type="text"
                placeholder="123456"
                maxLength={6}
                value={linkCode}
                onChange={(e) => setLinkCode(e.target.value)}
                className="flex-1 rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-sm text-zinc-100 placeholder-zinc-550 outline-none focus:border-white/20 transition-all"
              />
              <button
                onClick={linkDiscord}
                className="px-4 py-2 text-xs font-bold rounded-xl bg-white text-zinc-950 hover:bg-zinc-100 transition-all cursor-pointer"
              >
                Link
              </button>
            </div>
            {linkMessage && (
              <p className={`text-xs select-none ${linkMessage.type === "success" ? "text-emerald-400" : "text-red-400"}`}>
                {linkMessage.text}
              </p>
            )}
          </div>
        )}
      </div>

      {/* MCP Section */}
      <div className="rounded-2xl border border-white/10 bg-white/[0.02] p-6 space-y-4">
        <div className="flex items-center gap-3 select-none">
          <div className="p-2 bg-white/5 rounded-lg border border-white/10">
            <Key className="h-5 w-5 text-zinc-300" />
          </div>
          <div>
            <h3 className="text-md font-semibold text-zinc-100 font-bold">Model Context Protocol (MCP) Tokens</h3>
            <p className="text-xs text-zinc-400">
              Authorize local IDE extensions or AI assistants to read and edit tasks. 
              Read the <a href="/docs" className="text-white underline hover:text-zinc-350">integration guide</a> or view the package on <a href="https://www.npmjs.com/package/todo-flow-mcp" target="_blank" rel="noreferrer" className="text-white underline hover:text-zinc-350 font-bold">npm</a>.
            </p>
          </div>
        </div>

        {generatedToken ? (
          <div className="p-4 rounded-xl border border-emerald-500/20 bg-emerald-500/5 space-y-3 font-mono">
            <p className="text-xs text-emerald-450 font-semibold select-none">Copy your token now. You won't be able to see it again!</p>
            <div className="flex items-center gap-2 bg-zinc-900/50 border border-white/10 rounded-lg p-2.5 select-all">
              <span className="text-xs text-zinc-200 flex-1 truncate">{generatedToken}</span>
              <button
                onClick={() => copyToClipboard(generatedToken)}
                className="p-1.5 rounded-md text-zinc-400 hover:text-white hover:bg-white/10 transition-colors"
              >
                {copied ? <Check className="h-4 w-4 text-emerald-400" /> : <Copy className="h-4 w-4" />}
              </button>
            </div>

            {/* Quick config helper */}
            <div className="mt-4 pt-3 border-t border-white/5 space-y-2 text-zinc-400 select-text">
              <p className="text-[10px] font-bold text-zinc-200 select-none">Quick Integration (Claude Desktop Config):</p>
              <pre className="bg-zinc-950 p-2.5 rounded-lg border border-white/10 overflow-x-auto text-[10px] text-zinc-300">
{`{
  "mcpServers": {
    "todo-flow": {
      "command": "npx",
      "args": ["-y", "todo-flow-mcp"],
      "env": {
        "TODO_MCP_TOKEN": "${generatedToken}",
        "API_URL": "${typeof window !== "undefined" ? window.location.origin : "https://todo.jene.in"}/api/mcp"
      }
    }
  }
}`}
              </pre>
              <p className="text-[10px] text-zinc-500 select-none">
                Paste this into your configuration file. For other tools like Cursor, see the <a href="/docs" className="text-zinc-300 underline hover:text-white font-semibold">Docs</a>.
              </p>
            </div>

            <button
              onClick={() => setGeneratedToken(null)}
              className="px-4 py-1.5 text-xs font-bold rounded-lg bg-white/10 hover:bg-white/20 text-zinc-200 transition-all cursor-pointer"
            >
              Done
            </button>
          </div>
        ) : (
          <div className="space-y-4">
            <div className="flex gap-2 max-w-sm select-none">
              <input
                type="text"
                placeholder="Token description (e.g. Cursor)"
                value={newTokenName}
                onChange={(e) => setNewTokenName(e.target.value)}
                className="flex-1 rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-sm text-zinc-100 placeholder-zinc-550 outline-none focus:border-white/20 transition-all"
              />
              <button
                onClick={generateToken}
                className="px-4 py-2 text-xs font-bold rounded-xl bg-white text-zinc-950 hover:bg-zinc-100 transition-all cursor-pointer"
              >
                Generate
              </button>
            </div>

            <div className="space-y-2">
              <h4 className="text-xs font-bold text-zinc-400 uppercase tracking-wider select-none">Active Tokens</h4>
              {tokens.length === 0 ? (
                <p className="text-xs text-zinc-555 select-none">No active tokens. Generate one above to connect your AI coding companion.</p>
              ) : (
                <div className="divide-y divide-white/5 border border-white/10 rounded-xl overflow-hidden bg-zinc-950/20">
                  {tokens.map((t) => (
                    <div key={t.id} className="flex items-center justify-between p-3">
                      <div className="select-text">
                        <p className="text-xs font-semibold text-zinc-200">{t.name}</p>
                        <p className="text-[10px] text-zinc-550">Created {new Date(t.createdAt).toLocaleDateString()}</p>
                      </div>
                      <button
                        onClick={() => deleteToken(t.id)}
                        className="p-1.5 text-zinc-500 hover:text-red-450 rounded-lg hover:bg-red-500/10 transition-colors cursor-pointer"
                        title="Revoke Token"
                      >
                        <Trash2 className="h-4 w-4" />
                      </button>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
